# Generated by Django 3.2.20 on 2023-11-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eanaganavadiapp', '0002_chat_table_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat_table',
            old_name='FROM_ID',
            new_name='fromid',
        ),
        migrations.RenameField(
            model_name='chat_table',
            old_name='TO_ID',
            new_name='toid',
        ),
    ]
