# Generated by Django 3.2.20 on 2023-11-08 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Eanaganavadiapp', '0004_remove_assign_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_table',
            name='STAFF',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Eanaganavadiapp.staff_table'),
            preserve_default=False,
        ),
    ]
